import type { Metadata } from "next";
import "./globals.css";
import type { SanityImageSource } from "@sanity/image-url/lib/types/types";
import { client } from "./client";
import imageUrlBuilder from "@sanity/image-url";
import { type SanityDocument } from "next-sanity";
import ConsentAnalytics from "./components/ConsentAnalytics";

const PROFILE_QUERY = `*[_type == "profile"] | order(_createdAt desc) [0]`;
const options = { next: { revalidate: 30 } };
const SITE_URL = "https://okechuqu.com";

const { projectId, dataset } = client.config();
const urlFor = (source: SanityImageSource) =>
  projectId && dataset
    ? imageUrlBuilder({ projectId, dataset }).image(source)
    : null;

export async function generateMetadata(): Promise<Metadata> {
  const data = await client.fetch<SanityDocument>(PROFILE_QUERY, {}, options);

  if (!data) {
    return {
      metadataBase: new URL(SITE_URL),
      title: "Okechuqu's Portfolio",
      description: "Generated by Okechuqu's portfolio",
      alternates: { canonical: "/" },
      icons: null, // No favicon if data is unavailable
      // Default Twitter Card metadata
      twitter: {
        card: "summary_large_image", // Using "summary_large_image" since favicon is small
        title: "Okechuqu's Portfolio",
        description: "Generated by Okechuqu's portfolio",
      },
      openGraph: {
        title: "Okechuqu's Portfolio",
        description: "Generated by Okechuqu's portfolio",
        url: SITE_URL,
        type: "website",
      },
    };
  }

  const title = data.meta_title || "Okechuqu's Portfolio";
  const description =
    data.meta_description || "Generated by Okechuqu's portfolio";
  const faviconUrl = data.meta_favicon
    ? urlFor(data.meta_favicon)?.url()
    : null;
  const site = data.meta_x_handle || "@okechuqu"; // Replace with your X handle
  const socialImageUrl = data.meta_social_image
    ? urlFor(data.meta_social_image)?.url()
    : faviconUrl;

  return {
    metadataBase: new URL(SITE_URL),
    title,
    description,
    alternates: { canonical: "/" },
    icons: faviconUrl ? { icon: [faviconUrl] } : undefined,

    // Twitter Card metadata using favicon
    twitter: {
      card: "summary_large_image",
      title,
      description,
      ...(socialImageUrl && { images: [socialImageUrl] }),
      site,
    },
    // Open Graph metadata using favicon
    openGraph: {
      title,
      description,
      url: SITE_URL,
      type: "website",
      ...(socialImageUrl && { images: [{ url: socialImageUrl }] }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION && (
          <meta
            name="google-site-verification"
            content={process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION}
          />
        )}
        {process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION && (
          <meta
            name="msvalidate.01"
            content={process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION}
          />
        )}
      </head>
      <body>
        {children}
        <ConsentAnalytics />
      </body>
    </html>
  );
}
